"""push

Revision ID: c1b08c6b9249
Revises: 
Create Date: 2026-08-17 20:35:39.404171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b08c6b9249'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_hint', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_posts_expires_at'), 'spot_posts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_spot_posts_id'), 'spot_posts', ['id'], unique=False)
    op.create_index(op.f('ix_spot_posts_latitude'), 'spot_posts', ['latitude'], unique=False)
    op.create_index(op.f('ix_spot_posts_longitude'), 'spot_posts', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spot_posts_longitude'), table_name='spot_posts')
    op.drop_index(op.f('ix_spot_posts_latitude'), table_name='spot_posts')
    op.drop_index(op.f('ix_spot_posts_id'), table_name='spot_posts')
    op.drop_index(op.f('ix_spot_posts_expires_at'), table_name='spot_posts')
    op.drop_table('spot_posts')
    # ### end Alembic commands ###
